// 记忆核心 · 入料噪声闸门单测（P0）
//
// 背景：turn-stopping 抓的是「本会话新增的 user/assistant 消息」，而 DSH 会把运行时注入
// （环境快照 / team 广播 / teammate 原文 / 工具使用说明 / 被截断的上下文块）伪装成 user 消息。
// 旧实现全当正文喂给模型 → 待审队列出现「用户：<system-reminder> You are teammate」这类垃圾卡。
//
// 本文件锁定闸门行为：剥注入、挡碎片、挡糊标题；同时不能误伤真实对话。
import { test, after } from 'node:test'
import assert from 'node:assert/strict'
import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {
  stripRuntimeNoise, looksTruncated, hasUsableContent, deriveTitle, isUsableTitle,
  looksDurable, extractLastTurn, parseCaptureJson,
} from '../lib/capture.js'
import { runStandaloneCapture } from '../lib/capture-run.js'
import { listCards } from '../lib/vault.js'
import { closeAllDb } from '../lib/db.js'

const tmpRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'mc-noise-'))
after(async () => {
  closeAllDb()
  try { await fs.rm(tmpRoot, { recursive: true, force: true }) } catch { /* Windows 上句柄未释放时忽略 */ }
})

// -- stripRuntimeNoise -------------------------------------------------------

test('stripRuntimeNoise 剥掉 local-command-caveat / system-reminder 注入块，保留真实请求', () => {
  const raw = [
    '<local-command-caveat>Caveat: The messages below were generated by the user</local-command-caveat>',
    'Current runtime context. This snapshot supersedes earlier runtime-context snapshots.',
    '',
    '用户：1.图1点击安装和卸载 mcp 都没反应 2.我要下拉选择而不是展开',
  ].join('\n')
  const out = stripRuntimeNoise(raw)
  assert.ok(!out.includes('Caveat'))
  assert.ok(!out.includes('runtime context'))
  assert.ok(out.includes('点击安装和卸载'))
})

test('stripRuntimeNoise 剥掉 team 广播 / teammate 原文 / 工具说明标题行', () => {
  const raw = [
    'You are teammate "c" in an Agent Team.',
    '<team-broadcast>task-42 已完成，请勿重复处理</team-broadcast>',
    '# create-hook',
    'Create Codex hooks. Use when the user needs a Stop hook.',
    '用户：继续做 P0 修复。',
  ].join('\n')
  const out = stripRuntimeNoise(raw)
  assert.ok(!out.includes('task-42'), 'team 广播必须剥掉')
  assert.ok(!out.toLowerCase().includes('create-hook'), '工具说明标题必须剥掉')
  // 注：说明正文（"Create Codex hooks. Use when…"）目前不在剥离清单里 —— 它没有稳定的机器可辨前缀，
  // 硬加规则容易误伤真实英文内容；这类残句由「标题体检 + 人审」兜底。
  assert.ok(out.includes('继续做 P0 修复'))
})

test('stripRuntimeNoise 不误伤正常 markdown 标题与代码围栏', () => {
  const raw = '# 数据库选型结论\n\n采用 PostgreSQL + pgvector，理由是 JSONB 与团队熟悉度。\n\n```sql\nSELECT 1;\n```'
  const out = stripRuntimeNoise(raw)
  assert.ok(out.includes('# 数据库选型结论'))
  assert.ok(out.includes('采用 PostgreSQL'))
  assert.ok(out.includes('SELECT 1'))
})

// -- 碎片 / 内容判定 ---------------------------------------------------------

test('looksTruncated 认出错位开头与未完结结尾', () => {
  assert.equal(looksTruncated('`chema-form 当 external'), true) // 反引号开头
  assert.equal(looksTruncated('团队分工，'), true) // 未完结结尾
  assert.equal(looksTruncated('正常的标题'), false)
  assert.equal(looksTruncated(''), true)
})

test('hasUsableContent：只有注入残留的轮次不算有内容，真实长对话算', () => {
  const noiseOnly = stripRuntimeNoise('<system-reminder>You are a teammate "x" in an Agent Team. Report back when done with your task please.</system-reminder>')
  assert.equal(noiseOnly.trim(), '', '纯注入应被剥空')
  assert.equal(hasUsableContent(noiseOnly), false)
  const real = [
    '用户：帮我看看 DSH 记忆 MCP 的接入方式。官方文档写了三个可选的第三方记忆服务器，我想知道哪个更适合本地自研插件，以及是否值得把它们并进现有的记忆库。',
    '助手：Memorix 免 LLM 可纯启发式跑，Reference Memory 只有子串匹配，Engram 只管存储与项目选择。结论：当只读外部源最合适，写路径仍归自研插件。',
  ].join('\n')
  assert.equal(hasUsableContent(real), true)
})

test('looksDurable 仍能认出结构化知识，闲聊仍被长度门槛挡住', () => {
  // 闲聊样本刻意只测「长度门槛」这一层：信号表是有意放宽的（「前」「选」这类单字也算信号），
  // 不值得为了构造一条零信号的闲聊去削弱真实召回 —— 闲聊最终由 LLM 判定 + 审核中心兜底。
  const chat = '用户：随便聊聊天气怎么样啊今天挺好的我们出去走走吧反正也没什么正事要做的一整天都很闲，晚饭吃点什么好呢。'
  assert.equal(looksDurable(chat), false, '短闲聊不该被当成知识')
  const knowledge = '决定采用 SQLite 存储知识卡，理由是零依赖且支持 SQL 查询；步骤：1. 建表并开 WAL 2. 迁移旧 md 文件 3. 补审计日志表；配置项写进 config 表，让宿主与独立进程共用同一套解析顺序，避免切库后记忆被劈成两份、也很难再合并回来。'
  assert.equal(knowledge.length >= 120, true)
  assert.equal(looksDurable(knowledge), true)
})

// -- 标题派生 ---------------------------------------------------------------

test('deriveTitle 去掉说话人前缀、按句读断句、去掉连接性尾字符', () => {
  const t = deriveTitle('用户：数据库选型，最终确定使用 PostgreSQL。补充：主从复制用流复制。')
  assert.equal(t, '数据库选型，最终确定使用 PostgreSQL')
})

test('deriveTitle 跳过过短的装饰性首行，往后找像标题的一行', () => {
  const t = deriveTitle('# T\n\n这是一段足够长的正文内容，用于验证解析逻辑。')
  assert.ok(t.startsWith('这是一段足够长的正文内容'))
})

test('isUsableTitle：空 / 过短 / 碎片不合格，正常短标题合格', () => {
  assert.equal(isUsableTitle(''), false)
  assert.equal(isUsableTitle('T'), false)
  assert.equal(isUsableTitle('`che'), false)
  assert.equal(isUsableTitle('测试标题'), true)
  assert.equal(isUsableTitle('缓存策略'), true)
})

test('parseCaptureJson：标题糊掉时从正文派生，正文也派生不出才判无效', () => {
  const fixed = parseCaptureJson(JSON.stringify({
    save: true, title: '`che', kind: 'knowledge', tags: [],
    body: '缓存穿透用空值缓存解决，并增加随机过期防止雪崩。',
  }))
  assert.equal(fixed.save, true)
  assert.ok(fixed.title.startsWith('缓存穿透用空值缓存解决'), `应从正文派生标题，实际：${fixed.title}`)
  const dead = parseCaptureJson(JSON.stringify({ save: true, title: '`', kind: 'knowledge', tags: [], body: 'T' }))
  assert.equal(dead, null)
})

// -- 事件级剥离 -------------------------------------------------------------

test('extractLastTurn 丢掉纯注入的 user 消息，保留真实 user/assistant', () => {
  const events = [
    { type: 'user/message', data: { role: 'user', content: '<system-reminder>You are teammate "c" in an Agent Team.</system-reminder>' } },
    { type: 'user/message', data: { role: 'user', content: '把审核中心的待审卡清理一下。' } },
    { type: 'assistant/message', data: { role: 'assistant', content: '好的，我先列出 pending 列表再逐张判断。' } },
  ]
  const text = extractLastTurn(events)
  assert.ok(!text.includes('teammate'))
  assert.ok(text.includes('用户：把审核中心的待审卡清理一下。'))
  assert.ok(text.includes('助手：好的，我先列出 pending 列表'))
})

// -- 降级原文卡闸门（无 LLM 路径，MCP / CLI / hooks 共用） -------------------

test('runStandaloneCapture 拒绝「剥完就空」的注入文本，不写垃圾卡', async () => {
  const root = path.join(tmpRoot, 'vault-standalone')
  const noise = '<system-reminder>You are a teammate "c" in an Agent Team. Report back when your assigned task is finished.</system-reminder>'
  const out = await runStandaloneCapture(root, noise, { source: 'test' })
  assert.equal(out.ok, false)
  assert.equal(out.action, 'skipped')
  const cards = await listCards(root, { status: ['approved', 'pending', 'rejected'] })
  assert.equal(cards.length, 0, '注入文本不得落库')
})

test('runStandaloneCapture 正常文本仍能沉淀，且标题不再被硬切', async () => {
  const root = path.join(tmpRoot, 'vault-standalone-ok')
  const body = '用户：记忆卡的检索为什么要分两级？\n助手：决定把记忆卡的检索改成 CJK 整词 + 字符 bigram 两级，因为中文没有空格分词。步骤：1. 整词命中优先 2. bigram 兜底召回 3. 用反馈记录反哺排序。这样既省 token 又能避免语义漂移。'
  const out = await runStandaloneCapture(root, body, { source: 'test' })
  assert.equal(out.ok, true)
  const cards = await listCards(root, { status: ['approved', 'pending', 'rejected'] })
  assert.equal(cards.length, 1)
  // 标题派生自首个非碎片行（去掉「用户：」前缀），而不是被 slice(0,40) 硬切出的半句话
  assert.ok(cards[0].title.startsWith('记忆卡的检索为什么要分两级'), `标题应派生自首句，实际：${cards[0].title}`)
})
